export const productCategories = [
  {
    image: '/images/category/classy.png',
    key: 'classy',
  },
  {
    image: '/images/category/matic.png',
    key: 'matic',
  },
  {
    image: '/images/category/maxi.png',
    key: 'maxi',
  },
  {
    image: '/images/category/moped.png',
    key: 'moped',
  },
  {
    image: '/images/category/off-road.png',
    key: 'off-road',
  },
  {
    image: '/images/category/sport.png',
    key: 'sport',
  },
];

export const motorListHome = [
  {
    image: '/images/motor-home/lexylx-300x264.png',
    key: 'yamaha-lexi-lx',
    name: 'Yamaha Lexi LX',
    category: 'Maxi',
    price: 'Rp26.550.000',
  },
  {
    image: '/images/motor-home/matte-blue-1-300x265.png',
    key: 'yamaha-vixion',
    name: 'Yamaha Vixion',
    category: 'Sport',
    price: 'Rp30.765.000',
  },
  {
    image: '/images/motor-home/metallic-dark-grey-1-300x264.png',
    key: 'yamaha-mt25',
    name: 'Yamaha MT25',
    category: 'Sport',
    price: 'Rp59.855.000',
  },
  {
    image: '/images/motor-home/balck-red-300x264.png',
    key: 'yamaha-vega-force',
    name: 'Yamaha Vega Force',
    category: 'Moped',
    price: 'Rp17.750.000',
  },
  {
    image: '/images/motor-home/202503052220488174P45627-300x264.png',
    key: 'yamaha-gear-hybrid-s',
    name: 'Yamaha Gear Hybrid S',
    category: 'Matic',
    price: 'Rp21.700.000',
  },
  {
    image: '/images/motor-home/Silver-Yellow-300x264.png',
    key: 'yamaha-aerox-alpha',
    name: 'Yamaha Aerox Alpha',
    category: 'Maxi',
    price: 'Rp30.685.000',
  },
  {
    image: '/images/motor-home/YZ250FX-blue-300x264.png',
    key: 'yamaha-yz250fx',
    name: 'Yamaha YZ250FX',
    category: 'Off-Road',
    price: 'Rp98.900.000',
  },
  {
    image: '/images/motor-home/YZ250F-blue-300x264.png',
    key: 'yamaha-yz250f',
    name: 'Yamaha YZ250F',
    category: 'Off-Road',
    price: 'Rp105.500.000',
  },
  {
    image: '/images/motor-home/matte-black-300x265.png',
    key: 'yamaha-vixion-r',
    name: 'Yamaha Vixion R',
    category: 'Sport',
    price: 'Rp33.735.000',
  },
  {
    image: '/images/motor-home/metallic-cyan-1-300x264.png',
    key: 'yamaha-jupiter-z1',
    name: 'Yamaha Jupiter Z1',
    category: 'Moped',
    price: 'Rp21.520.000',
  },
  {
    image: '/images/motor-home/nmax-turbo-magma-elixir-dark-silver-300x264.png',
    key: 'yamaha-nmax-turbo',
    name: 'Yamaha Nmax Turbo',
    category: 'Maxi',
    price: 'Rp38.610.000',
  },
  {
    image: '/images/motor-home/CYAN-1-300x264.png',
    key: 'yamaha-mx-king',
    name: 'Yamaha MX King',
    category: 'Moped',
    price: 'Rp27.770.000',
  },
  {
    image: '/images/motor-home/nmax-neo-s-dull-blue-300x264.png',
    key: 'yamaha-nmax-neo',
    name: 'Yamaha Nmax Neo',
    category: 'Maxi',
    price: 'Rp33.440.000',
  },
  {
    image: '/images/motor-home/royal-blue-300x264.png',
    key: 'yamaha-fino-grande',
    name: 'Yamaha Fino Grande',
    category: 'Matic',
    price: 'Rp123.456.789',
  },
  {
    image: '/images/motor-home/cyan-yellow-300x264.png',
    key: 'yamaha-x-ride',
    name: 'Yamaha X-Ride',
    category: 'Matic',
    price: 'Rp21.180.000',
  },
  {
    image: '/images/motor-home/magma-black-300x264.png',
    key: 'yamaha-xmax-tech-max',
    name: 'Yamaha Xmax Tech Max',
    category: 'Maxi',
    price: 'Rp73.665.000',
  },
  {
    image: '/images/motor-home/metallic-black-300x246.png',
    key: 'yamaha-r25-abs',
    name: 'Yamaha R25 ABS',
    category: 'Sport',
    price: 'Rp75.500.000',
  },
  {
    image: '/images/motor-home/ice-performace-300x264.png',
    key: 'yamaha-r15-abs',
    name: 'Yamaha R15 ABS',
    category: 'Sport',
    price: 'Rp45.955.000',
  },
  {
    image: '/images/motor-home/lexi-s-abs-300x264.png',
    key: 'yamaha-lexi-lx-abs',
    name: 'Yamaha Lexi LX ABS',
    category: 'Maxi',
    price: 'Rp31.130.000',
  },
  {
    image: '/images/motor-home/Blue-Cybercity-300x264.png',
    key: 'yamaha-aerox-alpha-cybercity',
    name: 'Yamaha Aerox Alpha Cybercity',
    category: 'Maxi',
    price: 'Rp35.020.000',
  },
  {
    image: '/images/motor-home/metallic-dark-grey-300x264.png',
    key: 'yamaha-mt15',
    name: 'Yamaha MT15',
    category: 'Sport',
    price: 'Rp40.095.000',
  },
  {
    image: '/images/motor-home/2024011612393153967A35452-300x264.png',
    key: 'yamaha-lexi-lx-s',
    name: 'Yamaha Lexi LX S',
    category: 'Maxi',
    price: 'Rp28.065.000',
  },
  {
    image: '/images/motor-home/magma-black-2-300x264.png',
    key: 'yamaha-freego-connected',
    name: 'Yamaha Freego Connected',
    category: 'Matic',
    price: 'Rp24.565.000',
  },
  {
    image: '/images/motor-home/nmax-turbo-magma-black-1-300x264.png',
    key: 'yamaha-nmax-turbo-tech-max',
    name: 'Yamaha Nmax Turbo Tech Max',
    category: 'Maxi',
    price: 'Rp44.115.000',
  },
  {
    image: '/images/motor-home/racing-blue-300x246.png',
    key: 'yamaha-r25',
    name: 'Yamaha R25',
    category: 'Sport',
    price: 'Rp64.950.000',
  },
  {
    image: '/images/motor-home/black-espresso-300x264.png',
    key: 'yamaha-fino-premium',
    name: 'Yamaha Fino Premium',
    category: 'Matic',
    price: 'Rp123.456.789',
  },
  {
    image: '/images/motor-home/metallic-cyan-300x264.png',
    key: 'yamaha-mio-m3',
    name: 'Yamaha Mio M3',
    category: 'Matic',
    price: 'Rp18.700.000',
  },
  {
    image: '/images/motor-home/black-6-300x264.png',
    key: 'yamaha-wr155r',
    name: 'Yamaha WR155R',
    category: 'Off-Road',
    price: 'Rp41.925.000',
  },
  {
    image: '/images/motor-home/nmax-neo-s-white-300x264.png',
    key: 'yamaha-nmax-neo-s',
    name: 'Yamaha Nmax Neo S',
    category: 'Maxi',
    price: 'Rp34.440.000',
  },
  {
    image: '/images/motor-home/red-1-300x264.png',
    key: 'yamaha-fazzio-hybrid',
    name: 'Yamaha Fazzio Hybrid',
    category: 'Classy',
    price: 'Rp22.395.000',
  },
  {
    image: '/images/motor-home/2025030522215120818X79618-300x264.png',
    key: 'yamaha-gear-hybrid',
    name: 'Yamaha Gear Hybrid',
    category: 'Matic',
    price: 'Rp20.200.000',
  },
  {
    image: '/images/motor-home/nmax-turbo-ultimate-magma-black-300x264.png',
    key: 'yamaha-nmax-turbo-tech-max-ultimate',
    name: 'Yamaha Nmax Turbo Tech Max Ultimate',
    category: 'Maxi',
    price: 'Rp46.115.000',
  },
  {
    image: '/images/motor-home/premium-black-300x264.png',
    key: 'yamaha-xmax',
    name: 'Yamaha Xmax',
    category: 'Maxi',
    price: 'Rp68.410.000',
  },
  {
    image: '/images/motor-home/magma-black-1-300x264.png',
    key: 'yamaha-grand-filano-lux',
    name: 'Yamaha Grand Filano Lux',
    category: 'Classy',
    price: 'Rp29.010.000',
  },
  {
    image: '/images/motor-home/Blue-4-300x264.png',
    key: 'yamaha-yz125x',
    name: 'Yamaha YZ125X',
    category: 'Off-Road',
    price: 'Rp80.000.000',
  },
  {
    image: '/images/motor-home/pink-mauve-300x264.png',
    key: 'yamaha-fazzio-neo',
    name: 'Yamaha Fazzio Neo',
    category: 'Classy',
    price: 'Rp24.150.000',
  },
  {
    image: '/images/motor-home/titan-300x264.png',
    key: 'yamaha-fazzio-lux',
    name: 'Yamaha Fazzio Lux',
    category: 'Classy',
    price: 'Rp24.850.000',
  },
  {
    image: '/images/motor-home/Matte-Dark-Grey-Turbo-300x264.png',
    key: 'yamaha-aerox-turbo',
    name: 'Yamaha Aerox Turbo',
    category: 'Maxi',
    price: 'Rp40.635.000',
  },
  {
    image: '/images/motor-home/black-5-300x264.png',
    key: 'yamaha-r15',
    name: 'Yamaha R15',
    category: 'Sport',
    price: 'Rp41.925.000',
  },
  {
    image: '/images/motor-home/classic-tosca-300x264.png',
    key: 'yamaha-fino-sporty',
    name: 'Yamaha Fino Sporty',
    category: 'Matic',
    price: 'Rp123.456.789',
  },
  {
    image: '/images/motor-home/Matte-Dark-Grey-Ultimate.png',
    key: 'yamaha-aerox-turbo-ultimate',
    name: 'Yamaha Aerox Turbo Ultimate',
    category: 'Maxi',
    price: 'Rp42.815.000',
  },
  {
    image: '/images/motor-home/YZ250X-blue-300x264.png',
    key: 'yamaha-yz250x',
    name: 'Yamaha YZ250X',
    category: 'Off-Road',
    price: 'Rp95.700.000',
  },
  {
    image: '/images/motor-home/green-1-300x264.png',
    key: 'yamaha-grand-filano-neo',
    name: 'Yamaha Grand Filano Neo',
    category: 'Classy',
    price: 'Rp27.755.000',
  },
  {
    image: '/images/motor-home/sand-300x264.png',
    key: 'yamaha-freego',
    name: 'Yamaha Freego',
    category: 'Matic',
    price: 'Rp22.655.000',
  },
  {
    image: '/images/motor-home/light-blue-wanderlust-300x265.png',
    key: 'yamaha-xsr',
    name: 'Yamaha XSR',
    category: 'Sport',
    price: 'Rp39.795.000',
  },
];
