import { CategoryInterface, ProdukInterface } from './Produk.interfaces';

export const productCategories: CategoryInterface[] = [
  {
    image: '/images/category/classy.png',
    key: 'classy',
    name: 'Classy',
  },
  {
    image: '/images/category/matic.png',
    key: 'matic',
    name: 'Matic',
  },
  {
    image: '/images/category/maxi.png',
    key: 'maxi',
    name: 'Maxi',
  },
  {
    image: '/images/category/moped.png',
    key: 'moped',
    name: 'Moped',
  },
  {
    image: '/images/category/off-road.png',
    key: 'off-road',
    name: 'Off-Road',
  },
  {
    image: '/images/category/sport.png',
    key: 'sport',
    name: 'Sport',
  },
];

export const motorListHome: ProdukInterface[] = [
  {
    image: '/images/motor-home/lexylx-300x264.png',
    key: 'yamaha-lexi-lx',
    name: 'Yamaha Lexi LX',
    category: 'Maxi',
    price: 'Rp26.550.000',
    priceNum: 26550000,
    tags: ['lexi', 'lexi lx', 'lexi lx abs', 'maxi'],
    description: {
      specifications: [
        {
          section: 'mesin',
          title: [
            { key: 'engineType', value: 'Tipe Mesin' },
            { key: 'cylinderType', value: 'Susunan Silinder' },
            { key: 'transmissionType', value: 'Tipe Transmisi' },
            { key: 'clutchType', value: 'Tipe Kopling' },
            { key: 'fuelSystem', value: 'Sistem Bahan Bakar' },
            { key: 'oilCapacity', value: 'Kapasitas Oli Mesin' },
            { key: 'lubricationSystem', value: 'Sistem Pelumasan' },
            { key: 'starterSystem', value: 'Sistem Starter' },
            { key: 'maxTorque', value: 'Torsi Maksimum' },
            { key: 'maxPower', value: 'Daya Maksimum' },
            { key: 'cylinderVolume', value: 'Volume Silinder' },
            { key: 'compressionRatio', value: 'Perbandingan Kompresi' },
            { key: 'boreStroke', value: 'Diameter x Langkah' },
          ],
          desc: [
            { key: 'engineType', value: 'SOHC' },
            { key: 'cylinderType', value: 'Single Cylinder' },
            { key: 'transmissionType', value: 'V-belt automatic' },
            { key: 'clutchType', value: 'Single Dry Clutch' },
            { key: 'fuelSystem', value: 'Fuel Injection' },
            { key: 'oilCapacity', value: 'Total = 1.00 L ; Berkala = 0.90 L' },
            { key: 'lubricationSystem', value: 'Wet Sump' },
            { key: 'starterSystem', value: 'Electric starter' },
            { key: 'maxTorque', value: '14.2 Nm / 6500 rpm' },
            { key: 'maxPower', value: '11.3 kW / 8000 rpm' },
            { key: 'cylinderVolume', value: '155.9 cc' },
            { key: 'compressionRatio', value: '11.6:1' },
            { key: 'boreStroke', value: '58 x 58.7 mm' },
          ],
        },
        {
          section: 'dimensi',
          title: [
            { key: 'dimension', value: 'P x L x T' },
            { key: 'wheelbase', value: 'Jarak Sumbu Roda' },
            { key: 'groundClearance', value: 'Jarak Terendah Ke Tanah' },
            { key: 'seatHeight', value: 'Tinggi Tempat Duduk' },
            { key: 'weight', value: 'Berat Isi' },
            { key: 'fuelTankCapacity', value: 'Kapasitas Tangki Bensin' },
          ],
          desc: [
            { key: 'dimension', value: '1970 mm x 720 mm x 1135 mm' },
            { key: 'wheelbase', value: '1350 mm' },
            { key: 'groundClearance', value: '135 mm' },
            { key: 'seatHeight', value: '770 mm' },
            { key: 'weight', value: '118 kg' },
            { key: 'fuelTankCapacity', value: '4.2 L' },
          ],
        },
        {
          section: 'rangka',
          title: [
            { key: 'frameType', value: 'Tipe Rangka' },
            { key: 'frontSuspension', value: 'Suspensi Depan' },
            { key: 'rearSuspension', value: 'Tipe Suspensi Belakang' },
            { key: 'tireType', value: 'Tipe Ban' },
            { key: 'frontTire', value: 'Ban Depan' },
            { key: 'rearTire', value: 'Ban Belakang' },
            { key: 'frontBrake', value: 'Rem Depan' },
            { key: 'rearBrake', value: 'Rem Belakang' },
          ],
          desc: [
            { key: 'frameType', value: 'Underbone' },
            { key: 'frontSuspension', value: 'Telescopic Fork' },
            { key: 'rearSuspension', value: 'Unit Swing' },
            { key: 'tireType', value: 'Tubeless' },
            { key: 'frontTire', value: '90/90-14M/C 46P' },
            { key: 'rearTire', value: '100/90-14M/C 57P' },
            { key: 'frontBrake', value: 'Disc' },
            { key: 'rearBrake', value: 'Drum' },
          ],
        },
        {
          section: 'kelistrikan',
          title: [
            { key: 'ignitionSystem', value: 'Sistem Pengapian' },
            { key: 'batteryType', value: 'Tipe Battery' },
            { key: 'sparkPlugType', value: 'Tipe Busi' },
          ],
          desc: [
            { key: 'ignitionSystem', value: 'TCI' },
            { key: 'batteryType', value: 'YTZ6V' },
            { key: 'sparkPlugType', value: 'CPR8EA-9 / NGK' },
          ],
        },
      ],
    },
  },
  {
    image: '/images/motor-home/matte-blue-1-300x265.png',
    key: 'yamaha-vixion',
    name: 'Yamaha Vixion',
    category: 'Sport',
    price: 'Rp30.765.000',
    priceNum: 30765000,
  },
  {
    image: '/images/motor-home/metallic-dark-grey-1-300x264.png',
    key: 'yamaha-mt25',
    name: 'Yamaha MT25',
    category: 'Sport',
    price: 'Rp59.855.000',
    priceNum: 59855000,
  },
  {
    image: '/images/motor-home/balck-red-300x264.png',
    key: 'yamaha-vega-force',
    name: 'Yamaha Vega Force',
    category: 'Moped',
    price: 'Rp17.750.000',
    priceNum: 17750000,
  },
  {
    image: '/images/motor-home/202503052220488174P45627-300x264.png',
    key: 'yamaha-gear-hybrid-s',
    name: 'Yamaha Gear Hybrid S',
    category: 'Matic',
    price: 'Rp21.700.000',
    priceNum: 21700000,
  },
  {
    image: '/images/motor-home/Silver-Yellow-300x264.png',
    key: 'yamaha-aerox-alpha',
    name: 'Yamaha Aerox Alpha',
    category: 'Maxi',
    price: 'Rp30.685.000',
    priceNum: 30685000,
  },
  {
    image: '/images/motor-home/YZ250FX-blue-300x264.png',
    key: 'yamaha-yz250fx',
    name: 'Yamaha YZ250FX',
    category: 'Off-Road',
    price: 'Rp98.900.000',
    priceNum: 98900000,
  },
  {
    image: '/images/motor-home/YZ250F-blue-300x264.png',
    key: 'yamaha-yz250f',
    name: 'Yamaha YZ250F',
    category: 'Off-Road',
    price: 'Rp105.500.000',
    priceNum: 105500000,
  },
  {
    image: '/images/motor-home/matte-black-300x265.png',
    key: 'yamaha-vixion-r',
    name: 'Yamaha Vixion R',
    category: 'Sport',
    price: 'Rp33.735.000',
    priceNum: 33735000,
  },
  {
    image: '/images/motor-home/metallic-cyan-1-300x264.png',
    key: 'yamaha-jupiter-z1',
    name: 'Yamaha Jupiter Z1',
    category: 'Moped',
    price: 'Rp21.520.000',
    priceNum: 21520000,
  },
  {
    image: '/images/motor-home/nmax-turbo-magma-elixir-dark-silver-300x264.png',
    key: 'yamaha-nmax-turbo',
    name: 'Yamaha Nmax Turbo',
    category: 'Maxi',
    price: 'Rp38.610.000',
    priceNum: 38610000,
  },
  {
    image: '/images/motor-home/CYAN-1-300x264.png',
    key: 'yamaha-mx-king',
    name: 'Yamaha MX King',
    category: 'Moped',
    price: 'Rp27.770.000',
    priceNum: 27770000,
    additionalInfo: [
      'Yamaha MX King GP Monster Rp. 25.490.000',
      'Yamaha MX King WGP 60th Rp. 26.710.000',
    ],
    tags: ['moped', 'mx king'],
  },
  {
    image: '/images/motor-home/nmax-neo-s-dull-blue-300x264.png',
    key: 'yamaha-nmax-neo',
    name: 'Yamaha Nmax Neo',
    category: 'Maxi',
    price: 'Rp33.440.000',
    priceNum: 33440000,
  },
  {
    image: '/images/motor-home/royal-blue-300x264.png',
    key: 'yamaha-fino-grande',
    name: 'Yamaha Fino Grande',
    category: 'Matic',
    price: 'Rp123.456.789',
    priceNum: 123456789,
  },
  {
    image: '/images/motor-home/cyan-yellow-300x264.png',
    key: 'yamaha-x-ride',
    name: 'Yamaha X-Ride',
    category: 'Matic',
    price: 'Rp21.180.000',
    priceNum: 21180000,
  },
  {
    image: '/images/motor-home/magma-black-300x264.png',
    key: 'yamaha-xmax-tech-max',
    name: 'Yamaha Xmax Tech Max',
    category: 'Maxi',
    price: 'Rp73.665.000',
    priceNum: 73665000,
  },
  {
    image: '/images/motor-home/metallic-black-300x246.png',
    key: 'yamaha-r25-abs',
    name: 'Yamaha R25 ABS',
    category: 'Sport',
    price: 'Rp75.500.000',
    priceNum: 75500000,
  },
  {
    image: '/images/motor-home/ice-performace-300x264.png',
    key: 'yamaha-r15-abs',
    name: 'Yamaha R15 ABS',
    category: 'Sport',
    price: 'Rp45.955.000',
    priceNum: 45955000,
  },
  {
    image: '/images/motor-home/lexi-s-abs-300x264.png',
    key: 'yamaha-lexi-lx-abs',
    name: 'Yamaha Lexi LX ABS',
    category: 'Maxi',
    price: 'Rp31.130.000',
    priceNum: 31130000,
  },
  {
    image: '/images/motor-home/Blue-Cybercity-300x264.png',
    key: 'yamaha-aerox-alpha-cybercity',
    name: 'Yamaha Aerox Alpha Cybercity',
    category: 'Maxi',
    price: 'Rp35.020.000',
    priceNum: 35020000,
  },
  {
    image: '/images/motor-home/metallic-dark-grey-300x264.png',
    key: 'yamaha-mt15',
    name: 'Yamaha MT15',
    category: 'Sport',
    price: 'Rp40.095.000',
    priceNum: 40095000,
  },
  {
    image: '/images/motor-home/2024011612393153967A35452-300x264.png',
    key: 'yamaha-lexi-lx-s',
    name: 'Yamaha Lexi LX S',
    category: 'Maxi',
    price: 'Rp28.065.000',
    priceNum: 28065000,
  },
  {
    image: '/images/motor-home/magma-black-2-300x264.png',
    key: 'yamaha-freego-connected',
    name: 'Yamaha Freego Connected',
    category: 'Matic',
    price: 'Rp24.565.000',
    priceNum: 24565000,
  },
  {
    image: '/images/motor-home/nmax-turbo-magma-black-1-300x264.png',
    key: 'yamaha-nmax-turbo-tech-max',
    name: 'Yamaha Nmax Turbo Tech Max',
    category: 'Maxi',
    price: 'Rp44.115.000',
    priceNum: 44115000,
  },
  {
    image: '/images/motor-home/racing-blue-300x246.png',
    key: 'yamaha-r25',
    name: 'Yamaha R25',
    category: 'Sport',
    price: 'Rp64.950.000',
    priceNum: 64950000,
  },
  {
    image: '/images/motor-home/black-espresso-300x264.png',
    key: 'yamaha-fino-premium',
    name: 'Yamaha Fino Premium',
    category: 'Matic',
    price: 'Rp123.456.789',
    priceNum: 123456789,
  },
  {
    image: '/images/motor-home/metallic-cyan-300x264.png',
    key: 'yamaha-mio-m3',
    name: 'Yamaha Mio M3',
    category: 'Matic',
    price: 'Rp18.700.000',
    priceNum: 18700000,
  },
  {
    image: '/images/motor-home/black-6-300x264.png',
    key: 'yamaha-wr155r',
    name: 'Yamaha WR155R',
    category: 'Off-Road',
    price: 'Rp41.925.000',
    priceNum: 41925000,
  },
  {
    image: '/images/motor-home/nmax-neo-s-white-300x264.png',
    key: 'yamaha-nmax-neo-s',
    name: 'Yamaha Nmax Neo S',
    category: 'Maxi',
    price: 'Rp34.440.000',
    priceNum: 34440000,
  },
  {
    image: '/images/motor-home/red-1-300x264.png',
    key: 'yamaha-fazzio-hybrid',
    name: 'Yamaha Fazzio Hybrid',
    category: 'Classy',
    price: 'Rp22.395.000',
    priceNum: 22395000,
  },
  {
    image: '/images/motor-home/2025030522215120818X79618-300x264.png',
    key: 'yamaha-gear-hybrid',
    name: 'Yamaha Gear Hybrid',
    category: 'Matic',
    price: 'Rp20.200.000',
    priceNum: 20200000,
  },
  {
    image: '/images/motor-home/nmax-turbo-ultimate-magma-black-300x264.png',
    key: 'yamaha-nmax-turbo-tech-max-ultimate',
    name: 'Yamaha Nmax Turbo Tech Max Ultimate',
    category: 'Maxi',
    price: 'Rp46.115.000',
    priceNum: 46115000,
  },
  {
    image: '/images/motor-home/premium-black-300x264.png',
    key: 'yamaha-xmax',
    name: 'Yamaha Xmax',
    category: 'Maxi',
    price: 'Rp68.410.000',
    priceNum: 68410000,
  },
  {
    image: '/images/motor-home/magma-black-1-300x264.png',
    key: 'yamaha-grand-filano-lux',
    name: 'Yamaha Grand Filano Lux',
    category: 'Classy',
    price: 'Rp29.010.000',
    priceNum: 29010000,
  },
  {
    image: '/images/motor-home/Blue-4-300x264.png',
    key: 'yamaha-yz125x',
    name: 'Yamaha YZ125X',
    category: 'Off-Road',
    price: 'Rp80.000.000',
    priceNum: 80000000,
  },
  {
    image: '/images/motor-home/pink-mauve-300x264.png',
    key: 'yamaha-fazzio-neo',
    name: 'Yamaha Fazzio Neo',
    category: 'Classy',
    price: 'Rp24.150.000',
    priceNum: 24150000,
  },
  {
    image: '/images/motor-home/titan-300x264.png',
    key: 'yamaha-fazzio-lux',
    name: 'Yamaha Fazzio Lux',
    category: 'Classy',
    price: 'Rp24.850.000',
    priceNum: 24850000,
  },
  {
    image: '/images/motor-home/Matte-Dark-Grey-Turbo-300x264.png',
    key: 'yamaha-aerox-turbo',
    name: 'Yamaha Aerox Turbo',
    category: 'Maxi',
    price: 'Rp40.635.000',
    priceNum: 40635000,
  },
  {
    image: '/images/motor-home/black-5-300x264.png',
    key: 'yamaha-r15',
    name: 'Yamaha R15',
    category: 'Sport',
    price: 'Rp41.925.000',
    priceNum: 41925000,
  },
  {
    image: '/images/motor-home/classic-tosca-300x264.png',
    key: 'yamaha-fino-sporty',
    name: 'Yamaha Fino Sporty',
    category: 'Matic',
    price: 'Rp123.456.789',
    priceNum: 123456789,
  },
  {
    image: '/images/motor-home/Matte-Dark-Grey-Ultimate.png',
    key: 'yamaha-aerox-turbo-ultimate',
    name: 'Yamaha Aerox Turbo Ultimate',
    category: 'Maxi',
    price: 'Rp42.815.000',
    priceNum: 42815000,
  },
  {
    image: '/images/motor-home/YZ250X-blue-300x264.png',
    key: 'yamaha-yz250x',
    name: 'Yamaha YZ250X',
    category: 'Off-Road',
    price: 'Rp95.700.000',
    priceNum: 95700000,
  },
  {
    image: '/images/motor-home/green-1-300x264.png',
    key: 'yamaha-grand-filano-neo',
    name: 'Yamaha Grand Filano Neo',
    category: 'Classy',
    price: 'Rp27.755.000',
    priceNum: 27755000,
  },
  {
    image: '/images/motor-home/sand-300x264.png',
    key: 'yamaha-freego',
    name: 'Yamaha Freego',
    category: 'Matic',
    price: 'Rp22.655.000',
    priceNum: 22655000,
  },
  {
    image: '/images/motor-home/light-blue-wanderlust-300x265.png',
    key: 'yamaha-xsr',
    name: 'Yamaha XSR',
    category: 'Sport',
    price: 'Rp39.795.000',
    priceNum: 39795000,
  },
];
